Repository jphacks/C_2101, pull requests merged in 2021-11, with the labels that each got.

#131 ルームのアイキャッチ画像を設定可能にした
  app/src/main/java/dev/abelab/jphacks/api/request/RoomCreateRequest.java
  app/src/main/java/dev/abelab/jphacks/api/response/RoomResponse.java
  app/src/main/java/dev/abelab/jphacks/db/entity/Room.java
  app/src/main/java/dev/abelab/jphacks/db/entity/RoomExample.java
  app/src/main/java/dev/abelab/jphacks/service/AuthService.java
  app/src/main/java/dev/abelab/jphacks/service/RoomService.java
  app/src/main/java/dev/abelab/jphacks/service/UserService.java
  app/src/main/java/dev/abelab/jphacks/util/CloudStorageUtil.java
  app/src/main/resources/db/mapper/base/RoomBaseMapper.xml
  app/src/main/resources/db/migration/V1_0_1__alter_room.sql
  app/src/test/java/dev/abelab/jphacks/api/controller/AuthRestController_IT.java
  app/src/test/java/dev/abelab/jphacks/api/controller/RoomRestController_IT.java
  app/src/test/java/dev/abelab/jphacks/helper/sample/RoomSample.java
Labels: enhancement, backend

#135 ルーム作成時にアイキャッチ(サムネイル)画像を設定する
  client/src/api/@types/index.ts
  client/src/components/page/PageCreateSpace.tsx
  client/src/pages/make-room.tsx
Labels: frontend

#203 [fix] 参加登録していないときはexploreにリダイレクトする
  client/src/components/function/SocketRoot.tsx
Labels: bug, frontend

#204 たまに初期化ロード終わらないのを修正
  client/src/components/function/SocketRoot.tsx
Labels: frontend

#206 カメラ映像の下に発表者とか表示するようにした
  client/src/components/function/SkywayRoot.tsx
  client/src/components/page/space/cameraBlock/CameraBlock.tsx
  client/src/components/page/space/cameraBlock/CameraBlockContainer.tsx
  client/src/lib/hooks/useSyncTimetable.ts
Labels: enhancement, frontend

#211 コメントの自動スクロール実装
  client/src/components/page/space/commentBlock/CommentBlock.tsx
Labels: enhancement, frontend

#213 セクションの切り替え通知を追加
  client/src/components/page/space/commentBlock/CommentItem.tsx
  client/src/lib/hooks/useSyncComment.ts
  room-server/src/index.ts
Labels: enhancement, backend, frontend

#214 マイクとカメラのオンオフ切り替えできないときはツールチップ出すようにした
  client/src/components/page/space/configBlock/ConfigBlock.tsx
  client/src/components/page/space/configBlock/ConfigBlockContainer.tsx
  client/src/components/page/space/timerBlock/TimerBlock.tsx
  client/src/components/page/space/timerBlock/TimerBlockAdminController.tsx
Labels: enhancement, frontend

#215 カメラとマイクの選択機能実装
  client/src/components/function/SkywayRoot.tsx
  client/src/components/page/space/cameraBlock/CameraBlockContainer.tsx
  client/src/components/page/space/configBlock/ConfigBlockContainer.tsx
  client/src/components/page/space/configBlock/DeviceSelectModal.tsx
  client/src/lib/hooks/useStreamConfig.ts
  client/src/lib/navigator.ts
Labels: enhancement, frontend
